from variants.static_homogenous import StaticHomogenous
from variants.dynamic_homogenous import DynamicHomogenous

from variants.static_heterogenous import StaticHeterogenous
from variants.dynamic_heterogenous import DynamicHeterogenous